/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_yuexibo_jni_demo_Java2JNI */

#ifndef _Included_com_yuexibo_jni_demo_Java2JNI
#define _Included_com_yuexibo_jni_demo_Java2JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_yuexibo_jni_demo_Java2JNI
 * Method:    java2C
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_yuexibo_jni_1demo_Java2JNI_java2C
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
